name: ci

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Build the docker image
        run: docker build -t aniket036/nodejs-docker .
      -
        name: push to docker hub
        run: docker push aniket036/nodejs-docker:latest